[uwsgi]
# 监听端口
socket=0.0.0.0:8001
# 工作路径
chdir=/www/wwwroot/aliyundrive-qr-login
# 项目中wsgi.py文件的目录，相对于项目目录
wsgi-file=app.py
# callable的对象就是一个wsgi接口，如Flask中的app，是flask独有的配置项
callable=app
# 工作进程数
processes=2
# python 虚拟环境路径
virtualenv=/venvs/venv