upstream flask {
    server 127.0.0.1:5500;
}

server {
    listen       80;
    listen       [::]:80;
    server_name jihu.pp.ua;

    # Load configuration files for the default server block.
    # include /etc/nginx/default.d/*.conf;

    location /static {
        alias  /www/wwwroot/aliyundrive-qr-login/static;
    }

    location / {
        uwsgi_pass  flask;
        include     uwsgi_params;
    }

}
